### ISSUE TITLE
GoogleCamera: Video mode broken

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#32] opened 2016-01-13 12:22 UTC
I get a force-close in CM13 (20160112), when i switch to video in Google Camera app.
In CM13-Camera app, the app simply closes after switching to video. Reopening closes it immediately, as it remembers, that it was in video-mode.

Thanks for awesome-developing!

:-) AK

**Comment by cmorlok** [comment] 2016-01-13 12:59
Confirmed. FC on Snap as well.

**Comment by cmorlok** [comment] 2016-01-14 22:14
Video works with Google Camera and Camera2, but not with the new Snapdragon Camera.

**Comment by akamkomputer** [comment] 2016-01-15 09:44
For me, the video in com.google.android.GoogleCamera v3.1.021 doesn't work in 20160112.
I installed it with 6.0 opengapps-stock.
org.cyanogenmod.snap v2.0.002 doesn't work either.
:-) AK

**Comment by akamkomputer** [comment] 2016-01-15 12:07
Oh i didn't see that the 2016014 update is out. 
Doesn't show up in Cyanogenmod updates. Is that another issue?

**Comment by Kra1o5** [comment] 2016-01-15 12:12
Hi @halloalexkern ,

CM13.0 not have OTAs enable yet.

**Comment by cmorlok** [comment] 2016-01-19 07:57
Hi @halloalexkern. You can find the unofficial pre-releases on XDA.

**Comment by cmorlok** [comment] 2016-01-19 08:11
Some tests on build 20160117:
- good: Camera2 2.0.002 (com.android.camera2, 902c8585600a-30, builtin): Video recording works
- good: OpenCamera 1.27 (net.sourceforge.opencamera):  Video recording works
- good: GoogleCamera 2.5.052 (com.google.android.GoogleCamera, 2005148-30, latest Play Store version for our phone): Video recording works
- bad: GoogleCamera 3.1.021 (com.google.android.GoogleCamera, 2428808-30): FC immediately when switching to video mode
- bad: Snap 2.0.002 (com.cyanogenmod.snap, custom build): FC after first preview frame is shown in video mode

It might be because our camera only implements Camera1/HAL1. I will have to take a deeper look on how to solve that (if possible).

Logcat of GoogleCamera FC:

```
24085 24085 I CAM_SimpleModuleAgent: Creating module: VideoModule
24085 24111 I CameraDeviceState: Legacy camera service transitioning to state CONFIGURING
24085 24171 I RequestThread-0: Configure outputs: 0 surfaces configured.
  269 24124 D QCamera2HWI: int qcamera::QCamera2HardwareInterface::disableMsgType(int32_t) (0x10) : mMsgEnabled = 0xc0d
  269  1570 D QCamera2HWI: [KPI Perf] static void qcamera::QCamera2HardwareInterface::stop_preview(camera_device*): E PROFILE_STOP_PREVIEW
  269 24124 D QCamera2HWI: int qcamera::QCamera2HardwareInterface::stopPreview(): E
24085 24085 D CAM_Camera2OneCamMgr: Getting First FRONT Camera
24085 24085 D CAM_Camera2OneCamMgr: Getting First FRONT Camera
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=12200 audioChannels=1 audioCodec=1 audioSampleRate=8000 fileFormat=1 quality=2 videoBitRate=192000 videoCodec=2 videoFrameRate=30 videoFrameSize=176x144
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=156000 audioChannels=2 audioCodec=3 audioSampleRate=48000 fileFormat=2 quality=7 videoBitRate=512000 videoCodec=2 videoFrameRate=30 videoFrameSize=320x240
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=12200 audioChannels=1 audioCodec=1 audioSampleRate=8000 fileFormat=1 quality=3 videoBitRate=720000 videoCodec=2 videoFrameRate=30 videoFrameSize=352x288
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=156000 audioChannels=2 audioCodec=3 audioSampleRate=48000 fileFormat=2 quality=4 videoBitRate=2000000 videoCodec=2 videoFrameRate=30 videoFrameSize=720x480
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=156000 audioChannels=2 audioCodec=3 audioSampleRate=48000 fileFormat=2 quality=5 videoBitRate=14000000 videoCodec=2 videoFrameRate=30 videoFrameSize=1280x720
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=156000 audioChannels=2 audioCodec=3 audioSampleRate=48000 fileFormat=2 quality=6 videoBitRate=20000000 videoCodec=2 videoFrameRate=30 videoFrameSize=1920x1080
24085 24085 D CAM_Camera2OneCamMgr: Getting First BACK Camera
24085 24085 D CAM_Camera2OneCamMgr: Getting First BACK Camera
24085 24222 I FFmpegExtractor: android-source:0xb825ff98
24085 24085 I CAM_Video2Module: resume
24085 24085 I CAM_Video2Module: openCamcorderDevice
24085 24085 I CAM_ViewfinderSV0: Stop and remove viewfinder.
24085 24085 D CAM_ViewfinderSV0: Hiding the surface view.
24085 24085 D CAM_ViewfinderSV0: Hidden.
24085 24222 I FFmpegExtractor: adjust mime(application/ogg -> audio/vorbis)
24085 24222 D FFmpegExtractor: suppoted codec(vorbis) by official Stagefright
  269 24124 D QCameraHWI_Mem: cancel_buffer: hdl =0xb7f5d830
  269 24124 D QCameraHWI_Mem: put buffer 0 successfully
24085 24222 D FFmpegExtractor: ffmpeg detected media content as 'audio/vorbis' with confidence 0.08
  269 24124 D QCameraHWI_Mem: put buffer 1 successfully
24085 24085 D CAM_Camera2OneCamMgr: Getting First BACK Camera
24085 24085 D CAM_CamDvcPrxPrvdr: Attempting to open camera device proxy: CameraId{Api2='0',Api1:0}
24085 24085 D CAM_MltiDeviceLife: [openDevice()] open(cameraId: 'CameraDeviceKey{mApiType: CAMERA_API2, mCameraId: CameraId{Api2='0',Api1:0}}')
24085 24085 D CAM_MltiDeviceLife: [openDevice()] Existing request with the same id.
  269 24124 D QCameraHWI_Mem: cancel_buffer: hdl =0xb803c928
  269 24124 D QCameraHWI_Mem: put buffer 2 successfully
24085 24085 D CAM_MltiDeviceLife: [openDevice()] Returning future.
24085 24085 I CAM_Vid2CdrDevOpener: Selected capture rate: NORMAL
24085 24085 D CAM_Vid2Settings: video quality setting: pref_video_quality_back_key=large
24085 24085 I CAM_Vid2CdrDevOpener: Selected video resolution: RES_1080P
  269 24124 D QCameraHWI_Mem: cancel_buffer: hdl =0xb809ed88
  269 24124 D QCameraHWI_Mem: put buffer 3 successfully
24085 24085 I CAM_Vid2CdrDevOpener: Selected preview size: 1280x720
  269 24124 D QCameraHWI_Mem: cancel_buffer: hdl =0xb809ef48
  269 24124 D QCameraHWI_Mem: put buffer 4 successfully
  269 24124 D QCameraHWI_Mem: cancel_buffer: hdl =0xb8049510
  269 24124 D QCameraHWI_Mem: put buffer 5 successfully
  269 24124 D QCameraHWI_Mem: put buffer 6 successfully
24085 24085 I CAM_Vid2CdrDevOpener: isVideoStabilizationSupported: false
24085 24240 I OMXClient: Using client-side OMX mux.
24085 24085 I CAM_Vid2CdrDevOpener: maxRecordingDurationSeconds: 0
24085 24085 I CAM_Vid2CdrDevOpener: maxTorchRecordingDurationSeconds: 0
24085 24085 I CAM_Vid2CdrDevOpener: CamcorderManager.openCamcorder
24085 24085 D CAM_CdrProfileFact: CamcorderProfile: audioBitRate=156000 audioChannels=2 audioCodec=3 audioSampleRate=48000 fileFormat=2 quality=6 videoBitRate=20000000 videoCodec=2 videoFrameRate=30 videoFrameSize=1920x1080
  269 24124 D QCamera2HWI: int qcamera::QCamera2HardwareInterface::stopPreview(): X
  269  1570 D QCamera2HWI: [KPI Perf] static void qcamera::QCamera2HardwareInterface::stop_preview(camera_device*): X
24085 24240 E OMXMaster: A component of name 'OMX.qcom.audio.decoder.aac' already exists, ignoring this one.
24085 24171 D Camera  : app passed NULL surface
24085 24085 I OMXClient: Using client-side OMX mux.
24085 24085 E MediaCodec: Failed to get encoder input buffer count!
24085 24085 D AndroidRuntime: Shutting down VM
24085 24171 W RequestThread-0: Jpeg surface is invalid, skipping...
24085 24085 E AndroidRuntime: FATAL EXCEPTION: main
24085 24085 E AndroidRuntime: Process: com.google.android.GoogleCamera, PID: 24085
24085 24085 E AndroidRuntime: java.lang.NullPointerException
24085 24085 E AndroidRuntime:   at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:213)
24085 24085 E AndroidRuntime:   at com.google.common.base.Optional.of(Optional.java:85)
24085 24085 E AndroidRuntime:   at com.android.camera.camcorder.media.PersistentInputSurfaceFactoryMncImpl.createPersistentInputSurface(PersistentInputSurfaceFactoryMncImpl.java:15)
24085 24085 E AndroidRuntime:   at com.android.camera.camcorder.CamcorderManagerImpl.openCamcorder(CamcorderManagerImpl.java:284)
24085 24085 E AndroidRuntime:   at com.android.camera.module.video2.Video2CamcorderDeviceOpener.openCamcorderDevice(Video2CamcorderDeviceOpener.java:247)
24085 24085 E AndroidRuntime:   at com.android.camera.module.video2.Video2Module.openCamcorderDevice(Video2Module.java:383)
24085 24085 E AndroidRuntime:   at com.android.camera.module.video2.Video2Module.resume(Video2Module.java:360)
24085 24085 E AndroidRuntime:   at com.android.camera.module.ForwardingModuleController.resume(ForwardingModuleController.java:36)
24085 24085 E AndroidRuntime:   at com.android.camera.app.CameraActivityControllerImpl.openModule(CameraActivityControllerImpl.java:3153)
24085 24085 E AndroidRuntime:   at com.android.camera.app.CameraActivityControllerImpl.onModeSelected(CameraActivityControllerImpl.java:1115)
24085 24085 E AndroidRuntime:   at com.android.camera.app.CameraAppUI.onPhotoVideoSwitchStarted(CameraAppUI.java:3108)
24085 24085 E AndroidRuntime:   at com.android.camera.ui.PhotoVideoModeSwitchView.switchMode(PhotoVideoModeSwitchView.java:315)
24085 24085 E AndroidRuntime:   at com.android.camera.ui.PhotoVideoModeSwitchView$4.onAnimationEnd(PhotoVideoModeSwitchView.java:251)
24085 24085 E AndroidRuntime:   at android.animation.AnimatorSet$AnimatorSetListener.onAnimationEnd(AnimatorSet.java:855)
24085 24085 E AndroidRuntime:   at android.animation.ValueAnimator.endAnimation(ValueAnimator.java:1239)
24085 24085 E AndroidRuntime:   at android.animation.ValueAnimator$AnimationHandler.doAnimationFrame(ValueAnimator.java:766)
24085 24085 E AndroidRuntime:   at android.animation.ValueAnimator$AnimationHandler$1.run(ValueAnimator.java:801)
24085 24085 E AndroidRuntime:   at android.view.Choreographer$CallbackRecord.run(Choreographer.java:858)
24085 24085 E AndroidRuntime:   at android.view.Choreographer.doCallbacks(Choreographer.java:670)
24085 24085 E AndroidRuntime:   at android.view.Choreographer.doFrame(Choreographer.java:603)
24085 24085 E AndroidRuntime:   at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:844)
24085 24085 E AndroidRuntime:   at android.os.Handler.handleCallback(Handler.java:739)
24085 24085 E AndroidRuntime:   at android.os.Handler.dispatchMessage(Handler.java:95)
24085 24085 E AndroidRuntime:   at android.os.Looper.loop(Looper.java:148)
24085 24085 E AndroidRuntime:   at android.app.ActivityThread.main(ActivityThread.java:5466)
24085 24085 E AndroidRuntime:   at java.lang.reflect.Method.invoke(Native Method)
24085 24085 E AndroidRuntime:   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
24085 24085 E AndroidRuntime:   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

``
```

**Comment by cmorlok** [comment] 2016-01-28 16:55
Fixed in build 2016/01/24.

**Comment by cmorlok** [comment] 2016-02-03 21:22
GoogleCamera 3.1.021 still FC when switching to video mode

**Comment by Kra1o5** [comment] 2016-02-03 21:24
Yes, now I use SnapCamera (HDR still pending).

**Comment by cmorlok** [comment] 2016-02-17 16:56
I have opened #53 for further HDR discussions

**Comment by stucki** [comment] 2016-05-30 22:00
This issue was moved to bq-dev/android_device_bq_piccolo#32

**Closed as completed by stucki** 2016-05-30 22:00 UTC
Labels: cm-13.0
