### ISSUE TITLE
Camera still not perfect

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#47] opened 2016-02-01 06:27 UTC
Cm13-160124:
1. Google Camera 3.1.021 still force closes when switching to video mode. (can't connect to the camera) - this wasn't fixable, right?
2. CM camera 2.0.002 force closes when i click on the gallery.

Can anybody reproduce this?

:-) AK

**Comment by piwats** [comment] 2016-02-01 06:39
Have you tried cm-13-20160131?

**Comment by 1tft** [comment] 2016-02-01 09:22
@halloalexkern 2.: Can't reproduce with cm-13-20160131. For me camera/gallery switching is working fine.

**Comment by cmorlok** [comment] 2016-02-03 21:21
Duplicate of #32.

**Closed as completed by cmorlok** 2016-02-03 21:21 UTC
Labels: cm-13.0

**Comment by stucki** [comment] 2016-05-30 22:36
This issue was moved to bq-dev/android_device_bq_piccolo#47
