### ISSUE TITLE
Freezes while Youtube playback

### ISSUE THREAD

**Issue by akamkomputer** [piccolo-dev/android_device_bq_piccolo#11] opened 2015-10-20 10:15 UTC
I had an issue in: cm-12.1-20151017-UNOFFICIAL-piccolo.zip

During youtube playback my phones freezes soon and only a press-all-keys-reset is helping. Once it rebooted by its own; Sometimes screen goes off after a while when pressing the power button. When you turn the screen back on it shows the unlock screen and then the home-screen (youtube was exited).

When i tried to get a adb logcat (plugged into USB) i could not reproduce that issue. When i disconnected the USB (power) the screen froze again.

Yesterday a had a similar freeze when opening Google Maps for the first time. I could not reproduce that. 

:-) AK

**Comment by akamkomputer** [comment] 2015-10-20 16:35
Also happens with the previous build.
Switching to AwesomePlayer (instead of NuPlayer) in Developer settings doesn't fix it.
It only happens in Youtube fullscreen mode (tilted screen) and not in the small view.
Downscaling the video-quality to 720p doesn't fix it neither does throttling the CPU-frequency.

Can anyone reproduce this?

:-/ AK

**Comment by Kra1o5** [comment] 2015-10-21 18:29
Hi,
@eloimuns can test it?, thanks.

**Comment by akamkomputer** [comment] 2015-10-22 12:51
FYI ... I digged a little bit deeper: 
- issue also with HTML5-Videos (non-fullscreen & fullscreen) 
- issue also with Facebook-autoplay-videos in the timeline ... (Facebook freezes, when you shortly stop at a autoplay-timeline video ... if you scroll by fast enough, you're most likely lucky.)
- issue is NOT with webpage-embedded Youtube videos (as with non-fullscreen-videos inside the Youtube app as described before)
- when the video is frozen and you hit the Home-button, the audio stops. The screen is still frozen – including UI-Elements (if currently visible). You might then be lucky in pressing the power-off button an the screen goes off (sometimes only a forced-restart helps). When you switch it on again you are at the Lockscreen and from there you get to the Homescreen-Launcher.

i tried AwesomePlayer in dev-options and Deactivate HW-Overlays ... with no effect. 

:-) AK

**Comment by Kra1o5** [comment] 2015-10-22 18:45
Hi, I tested today (except facebook part) with not luck to reproduce it.

**Comment by eloimuns** [comment] 2015-10-23 06:43
I can't reproduce this issue. I use facebook, youtube and 0 freezes.

**Comment by akamkomputer** [comment] 2015-10-24 11:11
_damn_ ... thanks. I'll try to reinstall ...

**Comment by akamkomputer** [comment] 2015-10-24 16:13
I started over with a fresh system. Problem is still there.

It happens also when device is plugged into a wallcharger – but not while connected to adb logcat via USB. When i unplug the USB it freezes soon after.

:-/ AK

**Comment by akamkomputer** [comment] 2015-10-26 12:55
I noticed, that my device also freezes after a while during Hangouts-chatting. (not Video-chat, just Text-chat; without pictures, just text)
Maybe a hardware-problem?
:-/ AK

**Comment by Kra1o5** [comment] 2015-10-26 13:00
Hi @halloalexkern ,

@eloimuns & me try to reproduce all errors you report without any luck.

So is really weird.

You can try making Hard Reset maybe its help (This erase all data on internal_sd & data partitions not on SDCard so if you do it, make a backup of any personal data first if you dont want to lose all the data).

Greetings

**Comment by antonioborondo** [comment] 2015-10-26 14:30
I have exactly the same freezing problem with YouTube and Facebook videos, but I can not reproduce it always. Its very annoying :-(

The official firmware version 1.2.4 teorically fix those problems, but I haven't check it yet (link in Spanish sorry): http://www.mibqyyo.com/comunidad/discussion/59280/actualizaci%C3%B3n-1-2-4-para-bq-aquaris-m5/

**Comment by Kra1o5** [comment] 2015-10-26 14:38
You can check it in english: http://www.mibqyyo.com/comunidad/discussion/59283/bq-aquaris-m5-1-2-4-update/p1

But nothing related to videos, only related to front camera videos.

**Comment by antonioborondo** [comment] 2015-10-26 14:40
I've seen that in people comments thread. There is not in the official changelog.

**Comment by Kra1o5** [comment] 2015-10-26 14:46
You are right @antonioborondo .

We are using latest CAF kernel branch & from bq kernel changes we are using 1.2.1 (latest available).

One log or dmesg can be really appreciate to point out the problem.

**Comment by antonioborondo** [comment] 2015-10-26 14:58
@Kra1o5 I'll try to figure out a way to get the log from my phone and put it on here ;-)

**Comment by Kra1o5** [comment] 2015-10-26 15:00
Thanks @antonioborondo :-) .

Random errors are often the most difficult to hunt.

**Comment by akamkomputer** [comment] 2015-10-27 19:30
I tried it exactly with that Hard-Reset – i didn't format the SD-Card.
I reinstalled the latest CM 12.1 built and started Youtube right away, before anything installed ... and i got immediately a freeze :-(

Here a video.
https://www.youtube.com/watch?v=uuXPt90To78

Any ideas how i can get a good log for that? 
It doesn't freeze when it's connected to USB and i „adb logcat“ it.
... and i just tested again: on power it' doesn't freeze.
When i unplug it freezes again. 

I also found out, that some videos don't freeze(!?) at all :-/  ... but the Star-Wars trailer always freezes.

Sometimes the UI freezes. (the Hangouts-issue.) i think, it' sometimes, when there is a animation somewhere on the screen; e.g. the spinning wheel.

:-) AK

**Comment by eloimuns** [comment] 2015-10-28 07:12
Hi @halloalexkern,

Can you try to get logcat using adb via wifi? Just enable option and in PC (same wifi network).

**Comment by akamkomputer** [comment] 2015-10-29 15:10
Wifi-logcat. Good idea.

Here you go.  A Error, Warning and Verbose-log.

https://www.dropbox.com/sh/7r04lj8n4ytrr7g/AAAurj3QqLnEQHUF_SBiPP8ga?dl=0

I marked the comments with **\* COMMENTS ***

I did't get a E/ for when the screen was freezing.
The Errorlog is best-commented.

for the Verbose-Log it was not really possible to get the exact position where it it froze – i tried 3 times ... somewhere near line 6600

:-) AK

**Comment by Kra1o5** [comment] 2015-10-29 15:44
Thanks @halloalexkern ,

We will take a look into it asap.

**Comment by magicdave1** [comment] 2015-10-29 16:01
Just wanted to let you guys know that I have the exactely same problems like @halloalexkern

**Comment by Kra1o5** [comment] 2015-10-29 16:11
@magicdave1 @antonioborondo @halloalexkern ,

What variant of model you have?

@eloimuns & me 16/2 white variant.

**Comment by magicdave1** [comment] 2015-10-29 16:13
16/2 black

**Comment by Kra1o5** [comment] 2015-10-29 17:01
@halloalexkern can you provide dmesg too?

You can do it with adb wifi.

Because I think the error is on kernel part.

Thanks in advanced

**Comment by antonioborondo** [comment] 2015-10-29 17:04
@Kra1o5 32/3 black

**Comment by Kra1o5** [comment] 2015-10-29 17:08
Thanks for the info @magicdave1 & @antonioborondo .

So we can discard variant problem.

**Comment by akamkomputer** [comment] 2015-10-30 13:28
I have the 16/2 black, too.

The dmsg is getting interesting. You can really see something happening here:

https://www.dropbox.com/sh/6hcakuhf93zeqk5/AAAoKtFBEEwaG0dBhQdD8MBUa?dl=0

I did 2 files with "tail -f dmsg" (and before that two where i just got the dmsg at different states and deleted the double lines)

I think that file ist most interesting: cont_dmsg_YT-Video_freezes.txt

Maybe also the part where the YT-ui was frozen during spinning wheel is interesting: cont_dmsg_YT-UI_freezes.txt

:-) AK

**Comment by Kra1o5** [comment] 2015-10-30 13:48
Thanks @halloalexkern .
We will check it asap.

**Comment by Kra1o5** [comment] 2015-10-30 18:44
@halloalexkern @antonioborondo @magicdave1 ,

New build is out, can you try it & report back the results? 

Thanks

**Comment by akamkomputer** [comment] 2015-10-31 10:41
@Kra1o5 
As far i i just tested it doesn't work, unfortunately. Still freezes. At least the video.

:-/ AK

**Comment by akamkomputer** [comment] 2015-10-31 10:59
https://dl.dropboxusercontent.com/u/99389807/Androidlogs/DMSG2/YT-VideoFreeze-with-b30.txt

**Comment by Kra1o5** [comment] 2015-10-31 15:27
ok thanks @halloalexkern ,

At least I know is video/mdss part.

We are working on it.

**Comment by akamkomputer** [comment] 2015-10-31 17:14
Is it possible, that the UI-freezes are gone? I couldn't provoke any yet on the new build.

:-) AK

**Comment by antonioborondo** [comment] 2015-11-03 18:07
@Kra1o5 I'm installing the new build in my device. I'm going to test it a few days and I'll let you know. Thanks a lot for your time!!! :smiley:

**Comment by antonioborondo** [comment] 2015-11-03 19:19
@Kra1o5 I'm sorry but video still freezes :pensive:

**Comment by akamkomputer** [comment] 2015-11-04 09:15
I also had another few UI-freezes. So they're not gone completely.

:-) AK

**Comment by Kra1o5** [comment] 2015-11-05 15:55
Thanks for the feedback @halloalexkern & @antonioborondo ,  we will look into it asap.

**Comment by Kra1o5** [comment] 2015-11-10 17:18
Hi @magicdave1 @antonioborondo @halloalexkern ,

Can you test: https://s.basketbuild.com/filedl/devs?dev=Kra1o5&dl=Kra1o5/bq/piccolo/Test/boot_video.img & report back the results?

Greetings

**Comment by akamkomputer** [comment] 2015-11-12 07:42
That pretty boot-image fixed it for me!

Youtube runs smooth now without crashes (as far as i tested it) and even the nasty UI-freezes i had yesterday in Google Drive, while zooming in and out images, are gone now! 

So nice! **Much kudos for you Sir!!**

:-) AK

**Comment by magicdave1** [comment] 2015-11-12 08:35
What to do with that boot_video.img? I think this is not for flashing via recovery, right?

**Comment by eloimuns** [comment] 2015-11-12 09:05
If you are using TWRP, in install zip,at bottom right you will have option
to flash image.

**Comment by akamkomputer** [comment] 2015-11-12 09:16
or: boot into bootloader (eg. activate USB-debugging and then in terminal: _adb reboot bootloader_)
then in terminal: **fastboot flash boot boot-video.img** (this should finish with no error-message and take two seconds)
then: **fastboot reboot** (to restart your device)

:-) AK

**Comment by Kra1o5** [comment] 2015-11-12 21:11
Thanks for the feedback @halloalexkern , I will wait for another confirmation to close the issue.

**Comment by magicdave1** [comment] 2015-11-12 22:44
Thanks for both of you for helping me put the img on my device. I've tried watching videos for a couple of minutes and so far it works for me too. I will report back if these freezes will occur again.

**Comment by Kra1o5** [comment] 2015-11-12 22:56
Thanks @magicdave1 , I close it now.

**Comment by antonioborondo** [comment] 2015-11-13 13:52
Thanks @Kra1o5 for the fix!!! Are you planning to deliver a new build with the latest changes? :smiley:

**Comment by Kra1o5** [comment] 2015-11-13 13:53
Hi @antonioborondo yes.

Probably tomorrow.

**Closed as completed by Kra1o5** 2015-11-13 13:53 UTC

**Comment by magicdave1** [comment] 2015-11-13 20:52
Just had a freeze again in youtube and chrome.

**Comment by Kra1o5** [comment] 2015-11-13 21:02
Weird.

**Comment by akamkomputer** [comment] 2015-11-13 21:28
I'm watching youtube videos all day long ;-) ... no more freezes. 
I had a random reboot yesterday – after the phone was running somehow warm, but no freezes, neither UI nor video.

:-) AK

**Comment by antonioborondo** [comment] 2015-11-20 14:11
Hi @Kra1o5, I've been testing the latest build since a couple of days ago and it seems to be working fine. Thanks a million!!! :smiley:
