### ISSUE TITLE
Radio FM

### ISSUE THREAD

**Issue by RetroMarioBros** [piccolo-dev/android_device_bq_piccolo#1] opened 2015-09-13 01:04 UTC

**Comment by Kra1o5** [comment] 2015-09-13 01:29
Camera FM?

What is this?

**Comment by RetroMarioBros** [comment] 2015-09-14 07:24
Sorry , radio fm not found

**Comment by RetroMarioBros** [comment] 2015-09-14 07:26
The batery not arrive to 100%
Is in 96%

**Comment by Kra1o5** [comment] 2015-09-14 07:59
Not found or not working correctly?

If is the second, is a know issue.

For battery is really weird I get 100% without problems.

**Comment by stucki** [comment] 2015-09-14 08:22
Hey @angelhp! Please create 1 ticket per issue. This one is about Camera FM. The status is, it works for 3 seconds only. I had in mind that @Kra1o5 already fixed this but it still seems to exist.

**Comment by Kra1o5** [comment] 2015-09-14 08:25
Yes @stucki .

But really is Radio FM not Camera is a typo error.

We have located the error on audio HAL & we are looking one method to fix it.

**Comment by stucki** [comment] 2015-09-14 08:44
Right. Can you fix the title of this ticket?

**Comment by Kra1o5** [comment] 2015-09-14 08:48
@stucki Fixed!

**Comment by DerSaxxe** [comment] 2015-09-18 20:21
Hello! FM-Radio doesn't crash but there is no output. Recording works. Thanks!

**Comment by Kra1o5** [comment] 2015-09-18 20:22
Yes, we have located the problem (audio HAL).

But not fixed yet.

**Comment by andy-de** [comment] 2015-09-27 15:42
Spirit 2 works fine. Only switching output from headphone to internal speaker does not work. Maybe it helps solving this issues.

**Comment by Kra1o5** [comment] 2015-09-28 11:07
Hi @andy-de ,

We have the issue located but thanks for the tip, people can use Spirit 2 as temporal workaround.

Greetings

**Comment by Kra1o5** [comment] 2015-10-31 22:37
By request of @stucki ,

More info about the issue.

Is located in audio.primary.msm8916.so (/system/lib/hw/).

It seems like stock lib make something on it to avoid cut audio on kernel suspend.

We have two options.

Fix it on kernel (sounds part) or try to fix it on audio HAL part (audio.primary.msm8916.so).

**Comment by piwats** [comment] 2015-11-01 00:18
The Yureka Plus (snapdragon 615) seems to not depend on audio.primary.msm8916.so.

**Comment by starvoid** [comment] 2015-12-14 09:31
Hi, the fix for this issue....

could be get from this kernel?

https://github.com/CyanogenMod/android_kernel_bq_msm8916

I'm not sure, but I guess that is for aquaris X5. 

The last change was 3 days ago. It seems an active develop

Thanks for your effort.

**Comment by piwats** [comment] 2015-12-26 23:44
20151221: FYI: When turning off radio in the fm radio app, one can see the following stirng via dmesg:

```
<11>[ 3906.722968] init: no such service 'fm_dl'
```

And some errors via logcat, most notably the first three outlined:

```
E/android_hardware_fm(16168): id(8000006) value: 40
E/        (16168): file name is: /etc/fm/fm_srch_af_th.conf
E/        (16168): could not open file for read
E/        (16168): Error in loading threshold file
```

```
W/ContextImpl(16168): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1358 android.content.ContextWrapper.sendBroadcast:383 com.caf.fmradio.FMRadioService.sendRecordServiceIntent:770 com.caf.fmradio.FMRadioService.startFM:903 com.caf.fmradio.FMRadioService.fmOn:1847 
```

```
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/        (  252): Failed to fetch the lookup information of the device 0000000A 
```

```
D/FMService(16168): In startFM
D/FMRadio (16168): Starting listener 33
D/FMRadio (16168): Received event. Count: 1
D/FMRadio (16168): Received <0>
D/FMRadio (16168): Got READY_EVENT
V/FMRadio (16168): RxEvtList: CURRENT-STATE : FMRxStarting ---> NEW-STATE : FMRxOn
D/FMService(16168): FmRxEvEnableReceiver
E/android_hardware_fm(16168): id(8000006) value: 40
E/        (16168): file name is: /etc/fm/fm_srch_af_th.conf
E/        (16168): could not open file for read
E/        (16168): Error in loading threshold file
I/MediaFocusControl(  772):  AudioFocus  requestAudioFocus() from android.media.AudioManager@685be55com.caf.fmradio.FMRadioService$19@11ae206a req=2flags=0x0
D/FMService(16168): FM registering for registerMediaButtonEventReceiver
D/FMService(16168): FMRadio: Requesting to start FM
D/FMService(16168): Audio source set it as headset
D/audio_hw_primary(  252): adev_set_parameters: enter: connect=1048576
D/audio_hw_primary(  252): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: handle_fm=1048580
D/audio_hw_fm(  252): audio_extn_fm_set_parameters: FM usecase
D/audio_hw_fm(  252): fm_start: enter
D/audio_hw_primary(  252): select_devices: out_snd_device(4: headphones) in_snd_device(0: )
W/msm8916_platform(  252): Codec backend bitwidth 16, samplerate 48000
D/hardware_info(  252): hw_info_append_hw_type : device_name = headphones
W/audio_hw_utils(  252): audio_extn_utils_update_stream_app_type_cfg: App type could not be selected. Falling back to default
I/audio_hw_primary(  252): select_devices Selected apptype: 69936
D/ACDB-LOADER(  252): ACDB -> send_audio_cal, acdb_id = 10, path =  0
D/ACDB-LOADER(  252): ACDB -> send_asm_topology
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AUDPROC_STREAM_TOPOLOGY_ID
D/ACDB-LOADER(  252): ACDB -> send_adm_topology
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TOPOLOGY_ID
D/ACDB-LOADER(  252): ACDB -> send_audtable
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AUDPROC_COMMON_TABLE
D/ACDB-LOADER(  252): ACDB -> AUDIO_SET_AUDPROC_CAL
D/ACDB-LOADER(  252): ACDB -> send_audvoltable
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AUDPROC_GAIN_DEP_STEP_TABLE
D/ACDB-LOADER(  252): ACDB -> AUDIO_SET_AUDPROC_VOL_CAL
D/ACDB-LOADER(  252): ACDB -> send_afe_cal
D/ACDB-LOADER(  252): ACDB -> ACDB_CMD_GET_AFE_COMMON_TABLE
D/        (  252): Failed to fetch the lookup information of the device 0000000A 
E/ACDB-LOADER(  252): Error: ACDB AFE returned = -19
D/ACDB-LOADER(  252): ACDB -> AUDIO_SET_AFE_CAL
D/ACDB-LOADER(  252): ACDB -> send_hw_delay : acdb_id = 10 path = 0
D/ACDB-LOADER(  252): ACDB -> ACDB_AVSYNC_INFO: ACDB_CMD_GET_DEVICE_PROPERTY
D/audio_hw_primary(  252): select_devices: done
D/audio_hw_fm(  252): fm_set_volume: (0.055912)
D/audio_hw_fm(  252): fm_set_volume: Setting FM volume to 459 
D/audio_hw_fm(  252): fm_start: exit: status(0)
D/audio_hw_primary(  252): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: routing=4
D/audio_hw_primary(  252): out_set_parameters: enter: usecase(1: low-latency-playback) kvpairs: fm_volume=0.0100000994
D/audio_hw_fm(  252): audio_extn_fm_set_parameters: set_fm_volume usecase
D/audio_hw_fm(  252): fm_set_volume: (0.010000)
D/audio_hw_fm(  252): fm_set_volume: Setting FM volume to 82 
D/FMService(16168): Sending Recording intent for = 1
W/ContextImpl(16168): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1358 android.content.ContextWrapper.sendBroadcast:383 com.caf.fmradio.FMRadioService.sendRecordServiceIntent:770 com.caf.fmradio.FMRadioService.startFM:903 com.caf.fmradio.FMRadioService.fmOn:1847 
D/FMService(16168): mAudioManager.setFmRadioOn done 
D/FmRxRdsData(16168): In rdsOn: RDS is true
E/android_hardware_fm(16168): id(800000f) value: 1
E/android_hardware_fm(16168): id(8000010)
D/FmRxRdsData(16168): In rdsOptions: rdsMask: 23
E/android_hardware_fm(16168): id(8000010) value: fffffff8
E/android_hardware_fm(16168): id(8000014) value: 1
D/FMService(16168): registerRdsGroupProcessing done, Status :true
D/FMService(16168): enableAutoAF: true
D/FmRxRdsData(16168): In rdsOn: RDS is true
E/android_hardware_fm(16168): id(800000f) value: 1
D/FmRxRdsData(16168): In enableAFjump: AFenable : true
E/android_hardware_fm(16168): id(8000010)
D/FmRxRdsData(16168): Currently set rds_group_mask : -8
E/android_hardware_fm(16168): id(800001b) value: 1
E/android_hardware_fm(16168): id(8000010)
D/FmRxRdsData(16168): After enabling the rds_group_mask is : -8
D/FMService(16168): enableAutoAF done, Status :true
E/android_hardware_fm(16168): id(8000012)
D/FMService(16168): getInternalAntenna: false
E/android_hardware_fm(16168): id(8000012) value: 0
D/FMService(16168): setInternalAntenna done, Status :true
D/FMRecordingReceiver(16195): Received intent: codeaurora.intent.action.FM
D/FMRecordingReceiver(16195): FM intent received
D/FMRecordingReceiver(16195): FM ON intent received
D/FMRecordingService(16195): FMRecording Service onCreate
D/FMRecordingService(16195): FMRecording Service onCreate
D/FMService(16168): tuneRadio:  103.6
D/FmRxControls(16168): ** Tune Using: 33
D/FmRxControls(16168): ** Returned: 0
D/FMRadio (16168): Received event. Count: 5
D/FMRadio (16168): Received <8>
D/FMRadio (16168): Got BELOW_TH_EVENT
D/FMService(16168): FmRxEvServiceAvailable
D/FMService(16168): FmRxEvServiceAvailable: Tuned frequency is below signal threshold level
D/FMRadio (16168): Received <1>
D/FMRadio (16168): Got TUNE_EVENT
D/FMService(16168): FmRxEvRadioTuneStatus: Tuned Frequency: 103600
D/FmSharedPreferences(16168): Save preferences 
D/FMRadio (16168): mServiceCallbacks.onTuneStatusChanged: 
D/FMService(16168): enableStereo: true
D/FMRadio (16168): Received <8>
D/FMRadio (16168): Got BELOW_TH_EVENT
D/FMService(16168): FmRxEvServiceAvailable
D/FMService(16168): FmRxEvServiceAvailable: Tuned frequency is below signal threshold level
D/FMRadio (16168): Received <11>
D/FMRadio (16168): Got MONO_EVENT
D/FMService(16168): FmRxEvStereoStatus: false
D/FMRadio (16168): mServiceCallbacks.onAudioUpdate :2
D/FMRadio (16168): Received <13>
D/FMRadio (16168): Got RDS_NOT_AVAL_EVENT
D/FMService(16168): FmRxEvRdsLockStatus: false
D/FMRadio (16168): mServiceCallbacks.onStationRDSSupported :false
```

**Comment by piwats** [comment] 2015-12-28 22:31
Does the FM Radio app from the bq firmware run on cm?

**Comment by Kra1o5** [comment] 2015-12-28 22:36
The problem is on audio HAL.

**Comment by piwats** [comment] 2015-12-28 23:20
Please excuse me, if I'm getting annoying.

I was looking the reference cynogenmod msm8939 device description files and noticed that they have a slightly different uevent.qcom.d file, where you can find the following line:

https://github.com/CyanogenMod/android_device_cyanogen_msm8939-common/blob/72c919fe35521ae0b907c1eb755ddd7c17c4e021/rootdir/etc/ueventd.qcom.rc#L138

```
/dev/msm_fm               0660   system     audio
```

via: https://github.com/CyanogenMod/android_device_cyanogen_msm8939-common/search?utf8=%E2%9C%93&q=fm

A quick search over at codeaurora (caf, msm sources or how else they are called) revealed, that they do something like this (via https://www.codeaurora.org/cgit/external/gigabyte/ag-gb-dsds-7227/plain/hardware/msm7k/libaudio-msm8660/AudioHardware.cpp)

```
#define FM_DEVICE  "/dev/msm_fm"
```

Do you know where "our" /dev/msm_fm has gone??

UPDATE: found a question to this, this one is obsolete, as radio from the kernel perspective is working, spirit radio app proves it.

**Comment by piwats** [comment] 2015-12-31 03:07
Looking at the repo for the Xiami ferrari (msm8939) - it seems they have a working fm radio -, I noticed the following:

There is a

```
init.qcom.fm.sh
```

Look here: https://github.com/dh-harald/android_device_xiaomi_ferrari/blob/cm-12.1/rootdir/etc/init.qcom.fm.sh

which makes use of the following files/blobs/binaries included also in the original bq firmware (init.qcom.rc.sh is also present in the bq firmware):

```
# FM
bin/fmconfig
bin/fmfactorytest
bin/fmfactorytestserver
bin/fm_qsoc_patches
bin/ftmdaemon
```

It is worth mentioning, that google is exploding when trying to search for "init.qcom.fm.sh" as it seems to "turn on" fm radio where there was none before.

Happy new year!

**Comment by piwats** [comment] 2016-01-20 23:13
Seems to work in CM-13 (cm-13-20160120) :+1:

**Comment by stucki** [comment] 2016-05-31 06:19
This issue was moved to bq-dev/android_device_bq_piccolo#87

**Closed as completed by stucki** 2016-05-31 06:19 UTC
Labels: cm-12.1
